//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDevGrp.ReduceFoodWaste.WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDevGrp.ReduceFoodWaste.WebApplication.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms and privacy policy..
        /// </summary>
        public static string AcceptTermsAndPrivacyPolicy {
            get {
                return ResourceManager.GetString("AcceptTermsAndPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation.
        /// </summary>
        public static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code.
        /// </summary>
        public static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation code must be given..
        /// </summary>
        public static string ActivationCodeMustBeGiven {
            get {
                return ResourceManager.GetString("ActivationCodeMustBeGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another household member to the household.
        /// </summary>
        public static string AddHouseholdMemberToHousehold {
            get {
                return ResourceManager.GetString("AddHouseholdMemberToHousehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business related error..
        /// </summary>
        public static string BusinessException {
            get {
                return ResourceManager.GetString("BusinessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove yourself as a household member..
        /// </summary>
        public static string CannotRemoveYourselfAsHouseholdMember {
            get {
                return ResourceManager.GetString("CannotRemoveYourselfAsHouseholdMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannet resolve a mail address from your identity..
        /// </summary>
        public static string CannotResolveMailAddressFromIdentity {
            get {
                return ResourceManager.GetString("CannotResolveMailAddressFromIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannet resolve a user name identifier from your identity..
        /// </summary>
        public static string CannotResolveUserNameIdentifierFromIdentity {
            get {
                return ResourceManager.GetString("CannotResolveUserNameIdentifierFromIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use cookies on this site to enhance your user experience. As you move forward, you agree to our use of cookies..
        /// </summary>
        public static string CookieConsent {
            get {
                return ResourceManager.GetString("CookieConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new household.
        /// </summary>
        public static string CreateHousehold {
            get {
                return ResourceManager.GetString("CreateHousehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dansk.
        /// </summary>
        public static string Danish {
            get {
                return ResourceManager.GetString("Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorOccurredProcessingRequest {
            get {
                return ResourceManager.GetString("ErrorOccurredProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value exceeds the maximum length of {1} characters..
        /// </summary>
        public static string ExceedsMaximumLength {
            get {
                return ResourceManager.GetString("ExceedsMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string Expires {
            get {
                return ResourceManager.GetString("Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login providers.
        /// </summary>
        public static string ExternalLoginProviders {
            get {
                return ResourceManager.GetString("ExternalLoginProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household.
        /// </summary>
        public static string Household {
            get {
                return ResourceManager.GetString("Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household member account.
        /// </summary>
        public static string HouseholdMemberAccount {
            get {
                return ResourceManager.GetString("HouseholdMemberAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household members.
        /// </summary>
        public static string HouseholdMembers {
            get {
                return ResourceManager.GetString("HouseholdMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using another service.
        /// </summary>
        public static string LogInUsingAnotherService {
            get {
                return ResourceManager.GetString("LogInUsingAnotherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account..
        /// </summary>
        public static string LogInUsingYourAccount {
            get {
                return ResourceManager.GetString("LogInUsingYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail address.
        /// </summary>
        public static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A [Name] membership is free of costs..
        /// </summary>
        public static string MembershipBasicBillingInformation {
            get {
                return ResourceManager.GetString("MembershipBasicBillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Name] membership includes:&lt;br&gt;- As a household member you can only manage and be member of one household.&lt;br&gt;&lt;br&gt;This membership is free..
        /// </summary>
        public static string MembershipBasicDescription {
            get {
                return ResourceManager.GetString("MembershipBasicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A [Name] membership for &lt;b&gt;[Price]&lt;/b&gt; per year..
        /// </summary>
        public static string MembershipDeluxeBillingInformation {
            get {
                return ResourceManager.GetString("MembershipDeluxeBillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Name] membership includes:&lt;br&gt;- As a household member you can only manage and be member of two households.&lt;br&gt;&lt;br&gt;Membership costs &lt;b&gt;[Price]&lt;/b&gt; per year..
        /// </summary>
        public static string MembershipDeluxeDescription {
            get {
                return ResourceManager.GetString("MembershipDeluxeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given membership name &apos;{0}&apos; is unknown to the system..
        /// </summary>
        public static string MembershipNameUnknownToSystem {
            get {
                return ResourceManager.GetString("MembershipNameUnknownToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A [Name] membership for &lt;b&gt;[Price]&lt;/b&gt; per year..
        /// </summary>
        public static string MembershipPremiumBillingInformation {
            get {
                return ResourceManager.GetString("MembershipPremiumBillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Name] membership includes:&lt;br&gt;- As a household member you can manage and be member of multiple households.&lt;br&gt;&lt;br&gt;Membership costs &lt;b&gt;[Price]&lt;/b&gt; per year..
        /// </summary>
        public static string MembershipPremiumDescription {
            get {
                return ResourceManager.GetString("MembershipPremiumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to renew your membership..
        /// </summary>
        public static string MembershipRenewNotPossible {
            get {
                return ResourceManager.GetString("MembershipRenewNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to upgrade your membership..
        /// </summary>
        public static string MembershipUpgradeNotPossible {
            get {
                return ResourceManager.GetString("MembershipUpgradeNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to start using {0}.
        /// </summary>
        public static string PleaseLogIn {
            get {
                return ResourceManager.GetString("PleaseLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare your household member account.
        /// </summary>
        public static string PrepareHouseholdMemberAccount {
            get {
                return ResourceManager.GetString("PrepareHouseholdMemberAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The privacy policies has not been accepted..
        /// </summary>
        public static string PrivacyPoliciesHasNotBeenAccepted {
            get {
                return ResourceManager.GetString("PrivacyPoliciesHasNotBeenAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minimize Food Waste Project.
        /// </summary>
        public static string ReduceFoodWasteProject {
            get {
                return ResourceManager.GetString("ReduceFoodWasteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} credential from your account..
        /// </summary>
        public static string RemoveCredentialFromYourAccount {
            get {
                return ResourceManager.GetString("RemoveCredentialFromYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository error in {0}..
        /// </summary>
        public static string RepositoryException {
            get {
                return ResourceManager.GetString("RepositoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System critical error..
        /// </summary>
        public static string SystemException {
            get {
                return ResourceManager.GetString("SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to create your first household.
        /// </summary>
        public static string TimeToCreateYourFirstHousehold {
            get {
                return ResourceManager.GetString("TimeToCreateYourFirstHousehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to prepare your household member account.
        /// </summary>
        public static string TimeToPrepareYourHouseholdMemberAccount {
            get {
                return ResourceManager.GetString("TimeToPrepareYourHouseholdMemberAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain email address from your login account..
        /// </summary>
        public static string UnableToObtainEmailAddressFromService {
            get {
                return ResourceManager.GetString("UnableToObtainEmailAddressFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string UnsuccessfulLoginWithService {
            get {
                return ResourceManager.GetString("UnsuccessfulLoginWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required for this field..
        /// </summary>
        public static string ValueIsRequired {
            get {
                return ResourceManager.GetString("ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a valid mail address..
        /// </summary>
        public static string ValueNotValidMailAddress {
            get {
                return ResourceManager.GetString("ValueNotValidMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
    }
}
